name: reader_writer_lock
description: Simple reader-writer-lock implementation upon mutex package
version: 0.2.1
homepage: https://github.com/espresso3389/dart_reader_writer_lock

environment:
  sdk: ">=2.1.0 <3.0.0"

#dependencies:
#  mutex: ^1.0.3

dev_dependencies:
